version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5246:5246'
    environment:
      NODE_ENV: production
    networks:
      - app-network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'
    environment:
      API_URL: http://app:5246/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge